version: "3.7"
services:  
    # postgres used by airflow
    db:
        image: postgres:12.3-alpine
        container_name: films-db-dev
        networks:
            - default_net
        volumes: 
            - postgres_data:/var/lib/postgresql/data
            - ./pg-init-scripts:/docker-entrypoint-initdb.d
        env_file: postgres.env 
        ports:
            - "5455:5432"
    spark:
        image: bitnami/spark:3.1.2
        # https://docs.bitnami.com/tutorials/work-with-non-root-containers/
        user: root 
        hostname: spark
        networks:
            - default_net
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - /tmp:/data
            - ./spark/app:/usr/local/spark/app 
            - ./spark/resources:/usr/local/spark/resources 
        ports:
            - "8181:8080"
            - "7077:7077"

    spark-worker-1:
        image: bitnami/spark:3.1.2
        user: root
        networks:
            - default_net
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - /tmp:/data
            - ./spark/app:/usr/local/spark/app # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
            - ./spark/resources:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)

    spark-worker-2:
        image: bitnami/spark:3.1.2
        user: root
        networks:
            - default_net
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - /tmp:/data
            - ./spark/app:/usr/local/spark/app # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
            - ./spark/resources:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)


              #jupyter-spark:
              #image: jupyter/pyspark-notebook:spark-3.1.2
          #build: . 
          #container_name: films-jupyter-pyspark
          #networks:
          #- default_net
          #ports:
          #- "8888:8888"
          #- "4040-4080:4040-4080"
          #volumes:
          #- ./notebooks:/home/jovyan/work/notebooks/
          #- ./spark/resources/data:/home/jovyan/work/data/
            #- ./spark/resources/jars:/home/jovyan/work/jars/

volumes:
  postgres_data:

networks:
    default_net: 
